targets:
  $default:
    builders:
      drift_dev:
        options:
          override_hash_and_equals_in_result_sets: true
          use_column_name_as_json_key_when_defined_in_moor_file: true
          write_from_json_string_constructor: true
          raw_result_set_data: false
          named_parameters: false
          generate_manager: false # not used for these tests
          dialects:
            sqlite:
              version: "3.37"
              modules: [json1, fts5]
            postgres:
            mariadb:
