// Mocks generated by Mockito 5.4.4 from annotations
// in drift/test/test_utils/test_utils.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:drift/src/runtime/database/connection_user.dart' as _i4;
import 'package:drift/src/runtime/streams/store.dart' as _i2;
import 'package:drift/src/runtime/streams/update_rules.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StreamQueryStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamQueries extends _i1.Mock implements _i2.StreamQueryStore {
  @override
  _i3.Stream<T> registerStream<T extends Object>(
    _i2.QueryStreamFetcher<T>? fetcher,
    _i4.DatabaseConnectionUser? database,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerStream,
          [
            fetcher,
            database,
          ],
        ),
        returnValue: _i3.Stream<T>.empty(),
        returnValueForMissingStub: _i3.Stream<T>.empty(),
      ) as _i3.Stream<T>);

  @override
  _i3.Stream<Set<_i5.TableUpdate>> updatesForSync(
          _i5.TableUpdateQuery? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatesForSync,
          [query],
        ),
        returnValue: _i3.Stream<Set<_i5.TableUpdate>>.empty(),
        returnValueForMissingStub: _i3.Stream<Set<_i5.TableUpdate>>.empty(),
      ) as _i3.Stream<Set<_i5.TableUpdate>>);

  @override
  void handleTableUpdates(Set<_i5.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #handleTableUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
