name: drift_manager
description: A high-level query builder built with drift.
version: 1.0.0-wip
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  collection: ^1.19.1
  drift3_preview:
  drift_sqlite:
  meta: ^1.17.0
  sqlite3: ^3.0.0

dev_dependencies:
  build_runner: ^2.15.0
  drift_dev: ^2.33.0
  test: ^1.25.0
