targets:
  $default:
    builders:
      drift_dev:
        # Disable the default builder in favor of the modular builders configured
        # below.
        enabled: false

      drift_dev:analyzer:
        enabled: true
        options: &options
          named_parameters: true
          generate_manager: false # not yet ported
          dialects:
            sqlite:
              version: "3.39"
              modules: [fts5]
      drift_dev:modular:
        enabled: true
        options: *options
