name: drift
repository: https://github.com/simolus3/drift

packages:
 - docs
 - drift
 - drift_sqflite
 - drift_dev
 - sqlparser
 - examples/*
 - extras/benchmarks
 - extras/drift_postgres
 - extras/encryption
 - extras/integration_tests/*
 - extras/plugin_example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  check_format:
    run: dart format -o none --set-exit-if-changed .

  analyze:
    run: dart analyze --fatal-infos
    exec: {concurrency: 1}

  build:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: build_runner

  test:
    run: dart test
    exec: {concurrency: 1}
    select-package:
      depends-on: test
      ignore: drift_postgres # this is an integration test
