name: pg
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Simon Binder <oss@simonbinder.eu>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tests:
    path: ../tests
  postgres: ^2.4.1+2

dev_dependencies:
  test: ^1.16.0

dependency_overrides:
  drift:
    path: ../../../drift
  moor:
    path: ../../../moor
