import '../compiler.dart';
import '../dialect.dart';
import '../expressions/expression.dart';

/// A column constraint modifies a column to add e.g. a not-null requirement,
/// foreign keys, checks or additional information.
abstract base class ColumnConstraint implements SqlComponent {
  const ColumnConstraint._();

  /// Creates a column constraint generating dialect-specific SQL.
  const factory ColumnConstraint.custom(
    CustomComponent custom, {
    KnownSqlDialect? onlyOnDialect,
  }) = CustomColumnConstraint._;

  /// Creates a column constraint from its [sql] text.
  factory ColumnConstraint.customSql(String sql) {
    return ColumnConstraint.custom(CustomComponent(sql));
  }
}

/// A `PRIMARY KEY` constraint applied to a singe column.
final class ColumnPrimaryKeyConstraint extends ColumnConstraint {
  /// Whether to add an `AUTO INCREMENT` constraint to this primary key, meaning
  /// that values should be auto-generated by an increasing sequence.
  final bool isAutoIncrementing;

  /// @nodoc
  const ColumnPrimaryKeyConstraint({required this.isAutoIncrementing})
    : super._();

  @override
  void compileWith(StatementCompiler compiler) {
    compiler.addColumnPrimaryKeyConstraint(this);
  }
}

/// A `DEFAULT` constraint in SQL.
final class ColumnDefaultConstraint<T extends Object> extends ColumnConstraint {
  /// The default expression to use for the column when no value is given for
  /// inserts.
  final Expression<T> defaultExpression;

  /// Creates a `DEFAULT` constraint from the [defaultExpression].
  const ColumnDefaultConstraint(this.defaultExpression) : super._();

  @override
  void compileWith(StatementCompiler compiler) {
    compiler.addColumnDefaultConstraint(this);
  }
}

/// A `GENERATED AS` clause in SQL.
///
/// This information filled out by the generator to support generated or virtual
/// columns.
final class ColumnGeneratedAs extends ColumnConstraint {
  /// The expression that this column evaluates to.
  final Expression generatedAs;

  /// Wether this column is stored in the database, as opposed to being
  /// `VIRTUAL` and evaluated on each read.
  final bool stored;

  /// @nodoc
  const ColumnGeneratedAs(this.generatedAs, {this.stored = false}) : super._();

  @override
  void compileWith(StatementCompiler compiler) {
    compiler.addColumnGeneratedAs(this);
  }
}

/// A `UNIQUE` constraint on an individual column.
final class ColumnUniqueConstraint extends ColumnConstraint {
  /// @nodoc
  const ColumnUniqueConstraint() : super._();

  @override
  void compileWith(StatementCompiler compiler) {
    compiler.addColumnUniqueConstraint(this);
  }
}

/// An action for foreign keys controlling the behavior if the referenced value
/// is changed or deleted.
enum ReferenceAction {
  /// If the referenced value is updated or deleted, set the referencing column
  /// to null.
  setNull('SET NULL'),

  /// If the referenced value is updated or deleted, set the referencing column
  /// to its default.
  setDefault('SET DEFAULT'),

  /// Updates and deletions cascade along foreign keys.
  cascade('CASCADE'),

  /// Updates and deletions are prevented if an active reference exists.
  restrict('RESTRICT'),

  /// Don't do anything when a referenced value changes.
  noAction('NO ACTION');

  /// The default lexeme to use for this reference action in SQL.
  final String defaultLexeme;

  const ReferenceAction(this.defaultLexeme);
}

/// A constraint describing that a column references values in another row.
final class ColumnForeignKeyConstraint extends ColumnConstraint {
  /// The name of the table where a column is referenced.
  final String otherTableName;

  /// The name of the column being referenced.
  final String otherColumnName;

  /// How updates on the referenced value should propagate through the database.
  final ReferenceAction? onUpdate;

  /// How a referenced row being deleted should propagate through the database.
  final ReferenceAction? onDelete;

  /// Whether this foreign key reference was marked as deferrable and initially
  /// deferred, meaning that it is only checked at the end of transactions.
  final bool initiallyDeferred;

  /// @nodoc
  const ColumnForeignKeyConstraint({
    required this.otherTableName,
    required this.otherColumnName,
    this.onUpdate,
    this.onDelete,
    this.initiallyDeferred = false,
  }) : super._();

  @override
  void compileWith(StatementCompiler compiler) {
    compiler.addColumnForeignKeyConstraint(this);
  }
}

/// A check constraint on column.
///
/// For inserts and updates, the [check] condition is verified. If it doesn't
/// evaluate to `TRUE`, the database rejects the condition.
final class ColumnCheckConstraint extends ColumnConstraint {
  /// The condition to check for columns.
  final Expression<bool> check;

  /// @nodoc
  const ColumnCheckConstraint(this.check) : super._();

  @override
  void compileWith(StatementCompiler compiler) {
    compiler.addColumnCheckConstraint(this);
  }
}

/// A custom column constraint.
final class CustomColumnConstraint extends ColumnConstraint {
  /// The component generating text for this constraint.
  final CustomComponent component;

  /// If set to a non-null value, the constraint is only generated on this
  /// dialect and ignored on others.
  final KnownSqlDialect? onlyOnDialect;

  const CustomColumnConstraint._(this.component, {this.onlyOnDialect})
    : super._();

  @override
  void compileWith(StatementCompiler compiler) {
    component.compileWith(compiler);
  }
}
