import '../compiler.dart';
import '../expressions/custom.dart';
import '../expressions/expression.dart';
import '../statements/select.dart';
import '../type_converter.dart';
import 'column.dart';
import 'entities.dart';
import 'result_set.dart';

/// The common superclass for view classes generated by `drift_dev`.
abstract interface class GeneratedView<
  Row extends Object,
  Self extends GeneratedView<Row, Self>
>
    implements ResultSet<Row, Self> {
  /// For views defined in Dart, the select statement backing this view.
  ///
  /// Otherwise, drift generates [sqlDefinition] from the original SQL text.
  SelectStatement? get query;

  /// If [query] is not available, the generated SQL text for this view.
  CustomComponent? get sqlDefinition;

  /// The names of tables that this view is reading from.
  Set<String> get readsFrom;
}

/// A column in a [GeneratedView].
final class ViewColumn<T extends Object> extends SchemaColumn<T> {
  /// The expression backing this column in the view.
  ///
  /// This is not available for views defined in `.drift` files, since the
  /// entire `CREATE TABLE` statement is emitted.
  final Expression<T> expression;

  /// @nodoc
  ViewColumn({
    required super.name,
    required super.type,
    super.isNullable,
    required this.expression,
  });

  /// A view column for views defined in drift files.
  ///
  /// The [expression] is not provided for these.
  ViewColumn.forDriftFile({
    required super.name,
    required super.type,
    super.isNullable,
  }) : expression = const CustomExpression(CustomComponent(''));

  /// Applies a type converter to this column.
  ///
  /// This is mainly used by the generator.
  ViewColumnWithTypeConverter<D, T> withConverter<D>(
    TypeConverter<D, T?> converter,
  ) {
    return ViewColumnWithTypeConverter._(base: this, converter: converter);
  }
}

/// A [Expression] that has a [TypeConverter] attached to it.
///
/// This provides methods like [SchemaColumnWithTypeConverter.equalsValue],
/// which can be used to apply the type converter when building comparisons.
final class ViewColumnWithTypeConverter<D, S extends Object>
    extends ViewColumn<S>
    with SchemaColumnWithTypeConverter<D, S> {
  @override
  final TypeConverter<D, S?> converter;

  ViewColumnWithTypeConverter._({
    required this.converter,
    required ViewColumn<S> base,
  }) : super(
         name: base.name,
         type: base.type,
         isNullable: base.isNullable,
         expression: base.expression,
       );
}

/// Represents a `CREATE VIEW` statement in SQL.
final class CreateViewStatement extends CreateStatement<GeneratedView> {
  /// Create a statement that will `CREATE` the [entity] when issued.
  CreateViewStatement(super.entity, {super.ifNotExists});

  @override
  void compileWith(StatementCompiler compiler) {
    return compiler.addCreateViewStatement(this);
  }
}
