targets:
  $default:
    builders:
      # disables the SharedPartBuilder in favor of a PartBuilder from drift_dev
      drift_dev:
        enabled: false
      drift_dev:not_shared:
        enabled: true

      # Run built_value_generator when drift is done!
      built_value_generator:built_value:
        enabled: false

  run_built_value:
    dependencies: ['with_built_value']
    builders:
      # Disable all auto-applied builders from drift
      drift_dev:
        enabled: false
      drift_dev:preparing_builder:
        enabled: false
