import '../../internal/versioned_schema.dart';
import '../query_builder/schema/drop.dart';
import '../query_builder/schema/entities.dart';
import '../query_builder/schema/table.dart';
import '../query_builder/schema/view.dart';
import '../query_builder/statements/statement.dart';
import 'db_base.dart';

/// Signature of a function that will be invoked when a database is created.
typedef OnCreate = Future<void> Function(Migrator m);

/// Signature of a function that will be invoked when a database is upgraded
/// or downgraded.
/// In version upgrades: from < to
/// In version downgrades: from > to
typedef OnUpgrade = Future<void> Function(Migrator m, int from, int to);

/// Signature of a function that's called before a database is marked opened by
/// drift, but after migrations took place. This is a suitable callback to to
/// populate initial data or issue `PRAGMA` statements that you want to use.
typedef OnBeforeOpen = Future<void> Function(OpeningDetails details);

Future<void> _defaultOnCreate(Migrator m) => m.createAll();

Future<void> _defaultOnUpdate(Migrator m, int from, int to) async =>
    throw Exception(
      "You've bumped the schema version for your drift database "
      "but didn't provide a strategy for schema updates. Please do that by "
      'adapting the migrations getter in your database class.',
    );

/// Handles database migrations by delegating work to [OnCreate] and [OnUpgrade]
/// methods.
final class MigrationStrategy {
  /// Executes when the database is opened for the first time.
  final OnCreate onCreate;

  /// Executes when the database has been opened previously, but the last access
  /// happened at a different [GeneratedDatabase.schemaVersion].
  /// Schema version upgrades and downgrades will both be run here.
  final OnUpgrade onUpgrade;

  /// Executes after the database is ready to be used (ie. it has been opened
  /// and all migrations ran), but before any other queries will be sent. This
  /// makes it a suitable place to populate data after the database has been
  /// created or set sqlite `PRAGMAS` that you need.
  final OnBeforeOpen? beforeOpen;

  /// Construct a migration strategy from the provided [onCreate] and
  /// [onUpgrade] methods.
  const MigrationStrategy({
    this.onCreate = _defaultOnCreate,
    this.onUpgrade = _defaultOnUpdate,
    this.beforeOpen,
  });
}

/// Provides methods for generating SQL statements used to create, alter, or
/// drop elements in a database.
///
/// An instance of [Migrator] is created by drift internally to run the
/// migrations declared with a [MigrationStrategy] on your database class.
final class Migrator {
  /// The instance of the [GeneratedDatabase] class generated by `drift_dev`
  /// that this migrator is connected to.
  final GeneratedDatabase database;

  /// When non-null, use an old schema version in [createAll] and similar
  /// methods, making it easier to write sound migrations that don't always
  /// assume the latest database schema.
  final VersionedSchema? _fixedVersion;

  /// Used internally by drift when opening the database.
  Migrator(this.database, [this._fixedVersion]);

  Iterable<DatabaseSchemaEntity> get _allSchemaEntities {
    return _fixedVersion?.entities ?? database.allSchemaEntities;
  }

  /// Creates all tables, triggers, views, indexes and everything else defined
  /// in the database, if they don't exist.
  Future<void> createAll() async {
    for (final entity in _allSchemaEntities) {
      await create(entity);
    }
  }

  /// Creates the given [entity], which can be a table, a view, a trigger, an
  /// index or an [OnCreateQuery].
  Future<void> create(DatabaseSchemaEntity entity) async {
    if (entity is GeneratedTable) {
      await createTable(entity);
    } else if (entity is Trigger) {
      await createTrigger(entity);
    } else if (entity is Index) {
      await createIndex(entity);
    } else if (entity is OnCreateQuery) {
      final stmt = database.dialect.createCompiler();
      entity.definition.compileWith(stmt);
      await (await database.currentSession()).execute(
        stmt.statement.toStatementInfo(),
      );
    } else if (entity is GeneratedView) {
      await createView(entity);
    } else {
      throw ArgumentError('Unknown entity type: $entity');
    }
  }

  /// Drops and re-creates all views known to the database.
  ///
  /// Calling this may be useful in migrations that could potentially affect
  /// views. This includes changes to a view itself, but changes to tables that
  /// a view reads from may also warrant re-creating the view to make sure it's
  /// still valid.
  Future<void> recreateAllViews() async {
    for (final entity in _allSchemaEntities) {
      if (entity is GeneratedView) {
        await drop(entity);
        await createView(entity);
      }
    }
  }

  Future<void> _run(SqlStatement statement) async {
    await database.runStatement(statement);
  }

  /// Drops a table, trigger or index.
  Future<void> drop(DatabaseSchemaEntity entity) async {
    await _run(DropStatement.entity(entity, ifExists: true));
  }

  /// Executes the `CREATE TRIGGER` statement that created the [trigger].
  Future<void> createTrigger(Trigger trigger) async {
    await _run(CreateTriggerStatement(trigger, ifNotExists: true));
  }

  /// Executes a `CREATE INDEX` statement to create the [index].
  Future<void> createIndex(Index index) async {
    await _run(CreateIndexStatement(index, ifNotExists: true));
  }

  /// Creates the given table if it doesn't exist.
  Future<void> createTable(GeneratedTable table) async {
    await _run(CreateTableStatement(table, ifNotExists: true));
  }

  /// Creates the given view if it doesn't exist.
  Future<void> createView(GeneratedView view) async {
    await _run(CreateViewStatement(view, ifNotExists: true));
  }

  /// Deletes the table with the given name. Note that this function does not
  /// escape the [name] parameter.
  Future<void> deleteTable(String name) async {
    await _run(DropStatement('TABLE', name, ifExists: true));
  }

  /// Adds the given column to the specified table.
  Future<void> addColumn(GeneratedTable table, TableColumn column) async {
    await _run(AddColumnStatement(table, column));
  }

  /// Attempts to alter [table] to drop the [column].
  ///
  /// Please see the [sqlite3 documentation](https://sqlite.org/lang_altertable.html#altertabdropcol)
  /// on this functionality for possible caveats. In particular, be aware that
  /// indexed columns (also if they're part of a primary or unique key) or
  /// columns that are otherwise referenced in another table, trigger or view
  /// cannot be dropped.
  /// For columns only referenced in the [table] itself, calling [alterTable]
  /// with an empty [TableMigration] re-creates the table and thus drops the
  /// column while also re-creating relevant keys. If the column is referenced
  /// by another table, view, index or trigger, that entity needs to be updated
  /// first.
  ///
  /// Note that this method requires sqlite 3.35.0 or later.
  Future<void> dropColumn(GeneratedTable table, String column) async {
    await _run(DropColumnStatement(table, column));
  }

  /// Changes the name of a column in a [table].
  ///
  /// After renaming a column in a Dart table or a drift file and re-running the
  /// generator, you can use [renameColumn] in a migration step to rename the
  /// column for existing databases.
  ///
  /// The [table] argument must be set to the table enclosing the changed
  /// column. The [oldName] must be set to the old name of the [column] in SQL.
  /// For Dart tables, note that drift will transform `camelCase` column names
  /// in Dart to `snake_case` column names in SQL.
  ///
  /// __Important compatibility information__: [renameColumn] uses an
  /// `ALTER TABLE RENAME COLUMN` internally. Support for that syntax was added
  /// in sqlite version 3.25.0, released on 2018-09-15. When you're using
  /// Flutter and depend on `sqlite3_flutter_libs`, you're guaranteed to have
  /// that version. Otherwise, please ensure that you only use [renameColumn] if
  /// you know you'll run on sqlite 3.20.0 or later. In MariaDB support for that
  /// same syntax was added in MariaDB version 10.5.2, released on 2020-03-26.
  Future<void> renameColumn(
    GeneratedTable table,
    String oldName,
    TableColumn column,
  ) async {
    await _run(RenameColumnStatement(table, oldName, column));
  }

  /// Changes the [table] name from [oldName] to the current
  /// [GeneratedTable.entityName].
  ///
  /// After renaming a table in drift or Dart and re-running the generator, you
  /// can use [renameTable] in a migration step to rename the table in existing
  /// databases.
  Future<void> renameTable(GeneratedTable table, String oldName) async {
    await _run(RenameTableStatement(oldName, table));
  }

  /// Allows customizing step-by-step migrations (like the `OnUpgrade` callback
  /// returned by the generated `stepByStep` function) by invoking the [steps]
  /// function for each intermediate schema version from [from] until [to] is
  /// reached.
  ///
  /// This can be used to implement a custom `OnUpgrade` callback that runs
  /// additional checks before and after the migrations:
  ///
  /// ```dart
  /// onUpgrade: (m, from, to) async {
  ///  await customStatement('PRAGMA foreign_keys = OFF');
  ///
  ///  await transaction(
  ///    () => m.runMigrationSteps(
  ///      from: from,
  ///      to: to,
  ///      steps: migrationSteps(
  ///        from1To2: ...,
  ///        ...
  ///      ),
  ///    ),
  ///  );
  ///
  ///  if (kDebugMode) {
  ///    final wrongForeignKeys = await customSelect('PRAGMA foreign_key_check').get();
  ///    assert(wrongForeignKeys.isEmpty, '${wrongForeignKeys.map((e) => e.data)}');
  ///  }
  ///
  ///  await customStatement('PRAGMA foreign_keys = ON;');
  /// },
  /// ```
  ///
  /// Here, the `migrationSteps` method is generated by drift with the
  /// `drift_dev schema steps` command. For details, see the [documentation](https://drift.simonbinder.eu/docs/advanced-features/migrations/#step-by-step).
  Future<void> runMigrationSteps({
    required int from,
    required int to,
    required MigrationStepWithVersion steps,
  }) {
    return VersionedSchema.runMigrationSteps(
      migrator: this,
      from: from,
      to: to,
      steps: steps,
    );
  }
}

/// Provides information about whether migrations ran before opening the
/// database.
final class OpeningDetails {
  /// The schema version before the database has been opened, or `null` if the
  /// database has just been created.
  final int? versionBefore;

  /// The schema version after running migrations.
  final int versionNow;

  /// Whether the database has been created during this session.
  bool get wasCreated => versionBefore == null;

  /// Whether a schema upgrade was performed while opening the database.
  bool get hadUpgrade => !wasCreated && versionBefore != versionNow;

  /// Used internally by drift when opening a database.
  const OpeningDetails(this.versionBefore, this.versionNow)
    // Should use null instead of 0 for consistency
    : assert(versionBefore != 0);
}

/// Extension providing the [destructiveFallback] strategy.
extension DestructiveMigrationExtension on GeneratedDatabase {
  /// Provides a destructive [MigrationStrategy] that will delete and then
  /// re-create all tables, triggers and indices.
  ///
  /// To use this behavior, override the `migration` getter in your database:
  ///
  /// ```dart
  /// @DriftDatabase(...)
  /// class MyDatabase extends _$MyDatabase {
  ///   @override
  ///   MigrationStrategy get migration => destructiveFallback;
  /// }
  /// ```
  MigrationStrategy get destructiveFallback {
    return MigrationStrategy(
      onCreate: _defaultOnCreate,
      onUpgrade: (m, from, to) async {
        // allSchemaEntities are sorted topologically references between them.
        // Reverse order for deletion in order to not break anything.
        final reversedEntities = m._allSchemaEntities.toList().reversed;

        for (final entity in reversedEntities) {
          await m.drop(entity);
        }

        // Re-create them now
        await m.createAll();
      },
    );
  }
}
