name: moor_flutter
description: Flutter implementation of moor, a safe and reactive persistence library for Dart applications
version: 4.1.0
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  moor: ^4.0.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
