targets:
  $default:
    builders:
      drift_dev:
        options:
          drift3_preview: true
          generate_manager: false # not yet ported to drift3

          override_hash_and_equals_in_result_sets: true
          use_column_name_as_json_key_when_defined_in_moor_file: true
          raw_result_set_data: true
          named_parameters: true
          fatal_warnings: true
          dialects:
            - dialect: sqlite
              version: "3.37"
              modules:
                - json1
                - fts5
                - geopoly
            - dialect: postgres
