name: drift3
description: In-development preview of breaking changes planned for drift version 3.
version: 3.0.0-wip
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  meta: ^1.16.0
  collection: ^1.18.0

dev_dependencies:
  analyzer: ^8.4.1
  lints: ^6.0.0
  test: ^1.25.6
