FROM squidfunk/mkdocs-material
RUN apk add --no-cache g++
RUN apk add --no-cache gcc
RUN pip install mkdocs-macros-plugin
RUN pip install mkdocs-git-revision-date-localized-plugin
RUN pip install mkdocs-spellcheck[symspellpy]
