targets:
  $default:
    builders:
      drift_dev:
        options:
          generate_connect_constructor: true
          store_date_time_values_as_text: true
          sql:
            dialect: sqlite
            options:
              modules: [fts5]
