targets:
  $default:
    builders:
      drift_dev:
        options:
          # Relative path to the database file
          databases:
            default: lib/database.dart

          # Other Drift options
          dialects:
            sqlite:
              modules: [fts5]
              store_date_time_values_as_text: true
          preamble: |
            // coverage:ignore-file
