name: migrations_example
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  drift:

dev_dependencies:
  lints: ^2.0.0
  drift_dev:
  build_runner: ^2.0.0
  test: ^1.15.4

dependency_overrides:
  drift:
    path: ../../drift
  drift_dev:
    path: ../../drift_dev
  sqlparser:
    path: ../../sqlparser
