targets:
  $default:
    builders:
      drift_dev:
        options:
          compact_query_methods: true
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
          named_parameters: true
      build_web_compilers:entrypoint:
        generate_for:
          - web/**.dart
        options:
          compiler: dart2js
        dev_options:
          dart2js_args:
            - --no-minify
        release_options:
          dart2js_args:
            - -O4
