targets:
  $default:
    builders:
      moor_generator:
        options:
          generate_connect_constructor: true
          compact_query_methods: true
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
          named_parameters: true
          new_sql_code_generation: true
