// dart format width=80
import 'package:drift3/internal/versioned_schema.dart' as i0;
import 'package:drift3/drift.dart' as i1;

// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2() : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    categories,
    todoEntries,
    textEntries,
    todosInsert,
  ];
  late final Shape0 categories = Shape0(i0.VersionedTable(
    entityName: 'categories',
    withoutRowId: false,
    isStrict: false,
    tableConstraints: [],
    columns: [
      _column_0,
      _column_1,
      _column_2,
    ],
  ));
  late final Shape1 todoEntries = Shape1(i0.VersionedTable(
    entityName: 'todo_entries',
    withoutRowId: false,
    isStrict: false,
    tableConstraints: [],
    columns: [
      _column_0,
      _column_3,
      _column_4,
      _column_5,
    ],
  ));
  late final Shape2 textEntries = Shape2(i0.VersionedVirtualTable(
    entityName: 'text_entries',
    moduleAndArgs: 'fts5(description, content=todo_entries, content_rowid=id)',
    columns: [
      _column_6,
    ],
  ));
  final i1.Trigger todosInsert = i1.Trigger(
      'todos_insert',
      i1.CustomComponent(
          'CREATE TRIGGER todos_insert AFTER INSERT ON todo_entries BEGIN INSERT INTO text_entries ("rowid", description) VALUES (new.id, new.description);END'));
}

extension type Shape0(i0.VersionedTable _) implements i0.VersionedTable {
  i1.TableColumn<int> get id => columnsByName['id']! as i1.TableColumn<int>;
  i1.TableColumn<String> get name =>
      columnsByName['name']! as i1.TableColumn<String>;
  i1.TableColumn<int> get color =>
      columnsByName['color']! as i1.TableColumn<int>;
}
i1.TableColumn<int> _column_0(String aliasedName) => i1.TableColumn<int>(
    name: 'id',
    sqlType: i1.BuiltinDriftType.int,
    constraints: () => [
          const i1.ColumnPrimaryKeyConstraint(isAutoIncrementing: true),
          const i1.ColumnNotNullConstraint()
        ]);
i1.TableColumn<String> _column_1(String aliasedName) => i1.TableColumn<String>(
    name: 'name',
    sqlType: i1.BuiltinDriftType.text,
    constraints: () => [const i1.ColumnNotNullConstraint()]);
i1.TableColumn<int> _column_2(String aliasedName) => i1.TableColumn<int>(
    name: 'color',
    sqlType: i1.BuiltinDriftType.int,
    constraints: () => [const i1.ColumnNotNullConstraint()]);
extension type Shape1(i0.VersionedTable _) implements i0.VersionedTable {
  i1.TableColumn<int> get id => columnsByName['id']! as i1.TableColumn<int>;
  i1.TableColumn<String> get description =>
      columnsByName['description']! as i1.TableColumn<String>;
  i1.TableColumn<int> get category =>
      columnsByName['category']! as i1.TableColumn<int>;
  i1.TableColumn<DateTime> get dueDate =>
      columnsByName['due_date']! as i1.TableColumn<DateTime>;
}
i1.TableColumn<String> _column_3(String aliasedName) => i1.TableColumn<String>(
    name: 'description',
    sqlType: i1.BuiltinDriftType.text,
    constraints: () => [const i1.ColumnNotNullConstraint()]);
i1.TableColumn<int> _column_4(String aliasedName) =>
    i1.TableColumn<int>(name: 'category', sqlType: i1.BuiltinDriftType.int);
i1.TableColumn<DateTime> _column_5(String aliasedName) =>
    i1.TableColumn<DateTime>(
        name: 'due_date', sqlType: i1.BuiltinDriftType.dateTime);
extension type Shape2(i0.VersionedVirtualTable _)
    implements i0.VersionedVirtualTable {
  i1.SchemaColumn<String> get description =>
      columnsByName['description']! as i1.SchemaColumn<String>;
}
i1.TableColumn<String> _column_6(String aliasedName) => i1.TableColumn<String>(
    name: 'description',
    sqlType: i1.BuiltinDriftType.text,
    constraints: () => [i1.ColumnConstraint.customSql('')]);

final class Schema3 extends i0.VersionedSchema {
  Schema3() : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    categories,
    todoEntries,
    textEntries,
    todosInsert,
    todosDelete,
    todosUpdate,
  ];
  late final Shape0 categories = Shape0(i0.VersionedTable(
    entityName: 'categories',
    withoutRowId: false,
    isStrict: false,
    tableConstraints: [],
    columns: [
      _column_7,
      _column_1,
      _column_2,
    ],
  ));
  late final Shape1 todoEntries = Shape1(i0.VersionedTable(
    entityName: 'todo_entries',
    withoutRowId: false,
    isStrict: false,
    tableConstraints: [],
    columns: [
      _column_7,
      _column_3,
      _column_8,
      _column_5,
    ],
  ));
  late final Shape2 textEntries = Shape2(i0.VersionedVirtualTable(
    entityName: 'text_entries',
    moduleAndArgs: 'fts5(description, content=todo_entries, content_rowid=id)',
    columns: [
      _column_6,
    ],
  ));
  final i1.Trigger todosInsert = i1.Trigger(
      'todos_insert',
      i1.CustomComponent(
          'CREATE TRIGGER todos_insert AFTER INSERT ON todo_entries BEGIN INSERT INTO text_entries ("rowid", description) VALUES (new.id, new.description);END'));
  final i1.Trigger todosDelete = i1.Trigger(
      'todos_delete',
      i1.CustomComponent(
          'CREATE TRIGGER todos_delete AFTER DELETE ON todo_entries BEGIN INSERT INTO text_entries (text_entries, "rowid", description) VALUES (\'delete\', old.id, old.description);END'));
  final i1.Trigger todosUpdate = i1.Trigger(
      'todos_update',
      i1.CustomComponent(
          'CREATE TRIGGER todos_update AFTER UPDATE ON todo_entries BEGIN INSERT INTO text_entries (text_entries, "rowid", description) VALUES (\'delete\', new.id, new.description);INSERT INTO text_entries ("rowid", description) VALUES (new.id, new.description);END'));
}

i1.TableColumn<int> _column_7(String aliasedName) => i1.TableColumn<int>(
    name: 'id',
    sqlType: i1.BuiltinDriftType.int,
    constraints: () => [
          i1.ColumnConstraint.custom(i1.CustomComponent(
              'PRIMARY KEY AUTOINCREMENT',
              dialectSpecificSql: {})),
          const i1.ColumnNotNullConstraint()
        ]);
i1.TableColumn<int> _column_8(String aliasedName) => i1.TableColumn<int>(
    name: 'category',
    sqlType: i1.BuiltinDriftType.int,
    constraints: () => [
          i1.ColumnConstraint.custom(i1.CustomComponent(
              'REFERENCES categories (id)',
              dialectSpecificSql: {}))
        ]);

final class Schema4 extends i0.VersionedSchema {
  Schema4() : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    categories,
    todoEntries,
    textEntries,
    todosInsert,
    todosDelete,
    todosUpdate,
  ];
  late final Shape0 categories = Shape0(i0.VersionedTable(
    entityName: 'categories',
    withoutRowId: false,
    isStrict: false,
    tableConstraints: [],
    columns: [
      _column_9,
      _column_10,
      _column_11,
    ],
  ));
  late final Shape3 todoEntries = Shape3(i0.VersionedTable(
    entityName: 'todo_entries',
    withoutRowId: false,
    isStrict: false,
    tableConstraints: [],
    columns: [
      _column_9,
      _column_12,
      _column_13,
      _column_14,
    ],
  ));
  late final Shape2 textEntries = Shape2(i0.VersionedVirtualTable(
    entityName: 'text_entries',
    moduleAndArgs: 'fts5(description, content=todo_entries, content_rowid=id)',
    columns: [
      _column_6,
    ],
  ));
  final i1.Trigger todosInsert = i1.Trigger(
      'todos_insert',
      i1.CustomComponent(
          'CREATE TRIGGER todos_insert AFTER INSERT ON todo_entries BEGIN INSERT INTO text_entries ("rowid", description) VALUES (new.id, new.description);END'));
  final i1.Trigger todosDelete = i1.Trigger(
      'todos_delete',
      i1.CustomComponent(
          'CREATE TRIGGER todos_delete AFTER DELETE ON todo_entries BEGIN INSERT INTO text_entries (text_entries, "rowid", description) VALUES (\'delete\', old.id, old.description);END'));
  final i1.Trigger todosUpdate = i1.Trigger(
      'todos_update',
      i1.CustomComponent(
          'CREATE TRIGGER todos_update AFTER UPDATE ON todo_entries BEGIN INSERT INTO text_entries (text_entries, "rowid", description) VALUES (\'delete\', new.id, new.description);INSERT INTO text_entries ("rowid", description) VALUES (new.id, new.description);END'));
}

i1.TableColumn<int> _column_9(String aliasedName) => i1.TableColumn<int>(
    name: 'id',
    sqlType: i1.BuiltinDriftType.int,
    constraints: () =>
        [i1.ColumnConstraint.customSql('PRIMARY KEY AUTOINCREMENT NOT NULL')]);
i1.TableColumn<String> _column_10(String aliasedName) => i1.TableColumn<String>(
    name: 'name',
    sqlType: i1.BuiltinDriftType.text,
    constraints: () => [i1.ColumnConstraint.customSql('NOT NULL')]);
i1.TableColumn<int> _column_11(String aliasedName) => i1.TableColumn<int>(
    name: 'color',
    sqlType: i1.BuiltinDriftType.int,
    constraints: () => [i1.ColumnConstraint.customSql('NOT NULL')]);
extension type Shape3(i0.VersionedTable _) implements i0.VersionedTable {
  i1.TableColumn<int> get id => columnsByName['id']! as i1.TableColumn<int>;
  i1.TableColumn<String> get description =>
      columnsByName['description']! as i1.TableColumn<String>;
  i1.TableColumn<int> get category =>
      columnsByName['category']! as i1.TableColumn<int>;
  i1.TableColumn<int> get dueDate =>
      columnsByName['due_date']! as i1.TableColumn<int>;
}
i1.TableColumn<String> _column_12(String aliasedName) => i1.TableColumn<String>(
    name: 'description',
    sqlType: i1.BuiltinDriftType.text,
    constraints: () => [i1.ColumnConstraint.customSql('NOT NULL')]);
i1.TableColumn<int> _column_13(String aliasedName) => i1.TableColumn<int>(
    name: 'category',
    sqlType: i1.BuiltinDriftType.int,
    constraints: () =>
        [i1.ColumnConstraint.customSql('REFERENCES categories(id)')]);
i1.TableColumn<int> _column_14(String aliasedName) => i1.TableColumn<int>(
    name: 'due_date',
    sqlType: i1.BuiltinDriftType.int,
    constraints: () => [i1.ColumnConstraint.customSql('')]);
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2();
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3();
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4();
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
      from2To3: from2To3,
      from3To4: from3To4,
    ));
