# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

analyzer:
  # Jaspr has a custom lint package 'jaspr_lints', which needs the 'custom_lint' analyzer plugin.
  #
  # Unfortunately, running 'dart analyze' does not pick up the custom lints. Instead, you need to
  # run a separate command for this: `jaspr analyze`
  plugins:
    - custom_lint
  language:
    strict-casts: true
  exclude:
    - "**/*.g.dart"

#   exclude:
#     - path/to/excluded/files/**

# Uncomment the following section to enable or disable additional rules.

# linter:
#   rules:
#     camel_case_types: true

# For controlling Jaspr specific lint rules, we need a slightly different config.

# custom_lint:
#   rules:
#     prefer_html_methods: false

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
