import 'dart:convert';

/// A common supertype for all data classes generated by moor. Data classes are
/// immutable structures that represent a single row.
abstract class DataClass {
  const DataClass();

  // todo better docs, explain ValueSerializer

  /// Converts this object into a representation that can be encoded with
  /// [json].
  Map<String, dynamic> toJson(
      {ValueSerializer serializer = const ValueSerializer.defaults()});

  String toJsonString(
      {ValueSerializer serializer = const ValueSerializer.defaults()}) {
    return json.encode(toJson(serializer: serializer));
  }
}

/// Serializer responsible for mapping atomic types from and to json.
abstract class ValueSerializer {
  const ValueSerializer();
  const factory ValueSerializer.defaults() = _DefaultValueSerializer;

  dynamic toJson<T>(T value);
  T fromJson<T>(dynamic json);
}

class _DefaultValueSerializer extends ValueSerializer {
  const _DefaultValueSerializer();

  @override
  T fromJson<T>(json) {
    if (T == DateTime) {
      return DateTime.fromMillisecondsSinceEpoch(json as int) as T;
    }

    return json as T;
  }

  @override
  dynamic toJson<T>(T value) {
    if (value is DateTime) {
      return value.millisecondsSinceEpoch;
    }

    return value;
  }
}
